name: rate_me
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.2
  smooth_star_rating: 1.1.1
  image_picker: ^0.6.7+21
  fluttertoast: ^7.1.6
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo_main.png
    - lib/assets/title_main.png
    - lib/assets/rateME_logo.png
    - lib/assets/userAvatarTest.png
  